format = """
$shell\
$aws\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "cyan bold"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "bright-black"

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](white)($ahead_behind$stashed)]($style) "
style = "blue"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\) '
style = "purple"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow bold"

[shell]
format = '[\[$indicator\]]($style) '
style = "green bold"
disabled = false

[aws]
format = '[($profile)(\($region\) )]($style)'
