[colors]
ansi = [
    "#16181a",
    "#d11500",
    "#008b0c",
    "#997b00",
    "#0057d1",
    "#d100bf",
    "#008c99",
    "#7b8496"
]
background = "#ffffff"
brights = [
    "#16181a",
    "#d11500",
    "#008b0c",
    "#997b00",
    "#0057d1",
    "#d100bf",
    "#008c99",
    "#7b8496"
]

curosr_bg = "#16181a"
cursor_border = "#16181a"
cursor_fg = "#ffffff"
foreground = "#16181a"
selection_bg = "#acacac"
selection_fg = "#18181a"
split = "#008b0c"

[colors.indexed]
16 = "d17c00"
17 = "#a018ff"

[metadata]
name = "Cyberdream Light"
origin_url = "https://github.com/scottmckendry/cyberdream.nvim"
