[colors]
ansi = [
    "#16181a",
    "#ff6e5e",
    "#5eff6c",
    "#f1ff5e",
    "#5ea1ff",
    "#bd5eff",
    "#5ef1ff",
    "#d0d0d0"
]
background = "#16181a"
brights = [
    "#16181a",
    "#ff6e5e",
    "#5eff6c",
    "#f1ff5e",
    "#5ea1ff",
    "#bd5eff",
    "#5ef1ff",
    "#ffffff"
]

curosr_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#16181a"
foreground = "#ffffff"
selection_bg = "#3c4048"
selection_fg = "#ffffff"
split = "#5eff6c"

[colors.indexed]
16 = "#ffbd5e"
17 = "#ff6e5e"

[metadata]
name = "Cyberdream"
origin_url = "https://github.com/scottmckendry/cyberdream.nvim"
